# Generated by Django 5.0.2 on 2025-08-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('modern', 'Modern'), ('classic', 'Classic'), ('creative', 'Creative'), ('minimal', 'Minimal'), ('professional', 'Professional'), ('executive', 'Executive'), ('student', 'Student'), ('freelancer', 'Freelancer')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=20)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='templates/thumbnails/')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='templates/previews/')),
                ('layout_config', models.JSONField(default=dict, help_text='JSON configuration for layout')),
                ('styles', models.JSONField(default=dict, help_text='CSS styles and theme configuration')),
                ('sections', models.JSONField(default=dict, help_text='Available sections and their configuration')),
                ('is_premium', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'db_table': 'templates',
                'ordering': ['-is_featured', '-usage_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('icon', 'Icon'), ('image', 'Image'), ('logo', 'Logo'), ('background', 'Background'), ('decoration', 'Decoration')], max_length=20)),
                ('file', models.FileField(upload_to='templates/assets/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=False)),
                ('default_position', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Template Asset',
                'verbose_name_plural': 'Template Assets',
                'db_table': 'template_assets',
                'ordering': ['asset_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='#3498db', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Template Category',
                'verbose_name_plural': 'Template Categories',
                'db_table': 'template_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('header', 'Header'), ('about', 'About'), ('contact', 'Contact'), ('education', 'Education'), ('experience', 'Experience'), ('skills', 'Skills'), ('projects', 'Projects'), ('certifications', 'Certifications'), ('languages', 'Languages'), ('volunteer', 'Volunteer'), ('awards', 'Awards'), ('publications', 'Publications'), ('custom', 'Custom')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('layout_config', models.JSONField(default=dict)),
                ('styles', models.JSONField(default=dict)),
                ('content_config', models.JSONField(default=dict, help_text='Content field configuration')),
            ],
            options={
                'verbose_name': 'Template Section',
                'verbose_name_plural': 'Template Sections',
                'db_table': 'template_sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TemplateTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('colors', models.JSONField(default=dict)),
                ('typography', models.JSONField(default=dict)),
                ('spacing', models.JSONField(default=dict)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='templates/themes/')),
            ],
            options={
                'verbose_name': 'Template Theme',
                'verbose_name_plural': 'Template Themes',
                'db_table': 'template_themes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Template Usage',
                'verbose_name_plural': 'Template Usage',
                'db_table': 'template_usage',
                'ordering': ['-used_at'],
            },
        ),
    ]
