# Generated by Django 5.0.2 on 2025-08-26 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0003_initial'),
        ('templates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='templateasset',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='templates.template'),
        ),
        migrations.AddField(
            model_name='templatesection',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_sections', to='templates.template'),
        ),
        migrations.AddField(
            model_name='templatetheme',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='templates.template'),
        ),
        migrations.AddField(
            model_name='templateusage',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_usage', to='resumes.resume'),
        ),
        migrations.AddField(
            model_name='templateusage',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_history', to='templates.template'),
        ),
        migrations.AddField(
            model_name='templateusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_usage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='templatesection',
            unique_together={('template', 'section_type')},
        ),
    ]
