# Generated by Django 5.0.2 on 2025-08-26 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0001_initial'),
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='templates.template'),
        ),
    ]
