# Generated by Django 5.0.2 on 2025-08-26 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resumeexport',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='resumes.resume'),
        ),
        migrations.AddField(
            model_name='resumesection',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_sections', to='resumes.resume'),
        ),
        migrations.AddField(
            model_name='resumeshare',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='resumes.resume'),
        ),
        migrations.AddField(
            model_name='resumeversion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_versions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resumeversion',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='resumes.resume'),
        ),
        migrations.AlterUniqueTogether(
            name='resumesection',
            unique_together={('resume', 'section_type')},
        ),
        migrations.AlterUniqueTogether(
            name='resumeversion',
            unique_together={('resume', 'version_number')},
        ),
    ]
