const mongoose = require('mongoose');
const Template = require('../models/Template');

// MongoDB Atlas connection string
const MONGODB_URI = 'mongodb+srv://balwinder_cvgenix_1998:mAxGheQuqWAyvmzc@cvgenixdb.vrkl6u1.mongodb.net/?retryWrites=true&w=majority&appName=cvgenixdb';

async function createMoreTemplates() {
  try {
    await mongoose.connect(MONGODB_URI);
    console.log('✅ Connected to MongoDB Atlas');

    // Clear existing templates first
    await Template.deleteMany({});
    console.log('🗑️ Cleared existing templates');

    const templates = [
      {
        name: 'Software Engineer Resume',
        description: 'Modern software engineer resume with clean layout',
        category: 'Professional',
        renderEngine: 'canvas',
        thumbnail: 'https://via.placeholder.com/300x400/2c3e50/ffffff?text=Software+Engineer',
        preview: 'https://via.placeholder.com/800x1000/2c3e50/ffffff?text=Software+Engineer+Resume',
        metadata: {
          colorScheme: 'light',
          layout: 'two-column',
          complexity: 'moderate'
        },
        canvasData: {
          version: '5.1.0',
          objects: [
            {
              type: 'rect',
              left: 0,
              top: 0,
              width: 800,
              height: 1000,
              fill: '#ffffff',
              stroke: null,
              strokeWidth: 0,
              selectable: false,
              evented: false
            },
            {
              type: 'rect',
              left: 0,
              top: 0,
              width: 250,
              height: 1000,
              fill: '#2c3e50',
              stroke: null,
              strokeWidth: 0,
              selectable: false,
              evented: false
            },
            {
              type: 'text',
              left: 125,
              top: 50,
              width: 200,
              height: 40,
              text: 'JOHN SMITH',
              fontSize: 24,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#ffffff',
              textAlign: 'center',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 125,
              top: 90,
              width: 200,
              height: 20,
              text: 'Software Engineer',
              fontSize: 14,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#ecf0f1',
              textAlign: 'center',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 125,
              top: 150,
              width: 200,
              height: 20,
              text: 'CONTACT',
              fontSize: 16,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#ffffff',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 125,
              top: 180,
              width: 200,
              height: 60,
              text: 'john.smith@email.com\n(555) 123-4567\nSan Francisco, CA\nlinkedin.com/in/johnsmith',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#ecf0f1',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 125,
              top: 280,
              width: 200,
              height: 20,
              text: 'SKILLS',
              fontSize: 16,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#ffffff',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 125,
              top: 310,
              width: 200,
              height: 100,
              text: 'JavaScript, Python, React\nNode.js, MongoDB, AWS\nGit, Docker, Kubernetes\nAgile, Scrum, CI/CD',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#ecf0f1',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 300,
              top: 50,
              width: 450,
              height: 20,
              text: 'PROFESSIONAL SUMMARY',
              fontSize: 16,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 300,
              top: 80,
              width: 450,
              height: 60,
              text: 'Experienced software engineer with 5+ years developing scalable web applications. Passionate about clean code, agile methodologies, and continuous learning.',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#34495e',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 300,
              top: 160,
              width: 450,
              height: 20,
              text: 'EXPERIENCE',
              fontSize: 16,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 300,
              top: 190,
              width: 450,
              height: 40,
              text: 'Senior Software Engineer | TechCorp Inc. | 2020-Present',
              fontSize: 14,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 300,
              top: 230,
              width: 450,
              height: 60,
              text: '• Led development of microservices architecture serving 1M+ users\n• Improved application performance by 40% through code optimization\n• Mentored 3 junior developers and conducted code reviews',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#34495e',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 300,
              top: 320,
              width: 450,
              height: 40,
              text: 'Software Engineer | StartupXYZ | 2018-2020',
              fontSize: 14,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 300,
              top: 360,
              width: 450,
              height: 60,
              text: '• Developed full-stack web applications using React and Node.js\n• Implemented automated testing reducing bugs by 30%\n• Collaborated with design team to improve user experience',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#34495e',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 300,
              top: 450,
              width: 450,
              height: 20,
              text: 'EDUCATION',
              fontSize: 16,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 300,
              top: 480,
              width: 450,
              height: 40,
              text: 'Bachelor of Science in Computer Science\nUniversity of California, Berkeley | 2018',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#34495e',
              textAlign: 'left',
              selectable: true,
              evented: true
            }
          ]
        }
      },
      {
        name: 'Marketing Manager Resume',
        description: 'Professional marketing resume with modern design',
        category: 'Professional',
        renderEngine: 'canvas',
        thumbnail: 'https://via.placeholder.com/300x400/3498db/ffffff?text=Marketing+Manager',
        preview: 'https://via.placeholder.com/800x1000/3498db/ffffff?text=Marketing+Manager+Resume',
        metadata: {
          colorScheme: 'colorful',
          layout: 'single-column',
          complexity: 'moderate'
        },
        canvasData: {
          version: '5.1.0',
          objects: [
            {
              type: 'rect',
              left: 0,
              top: 0,
              width: 800,
              height: 1000,
              fill: '#ffffff',
              stroke: null,
              strokeWidth: 0,
              selectable: false,
              evented: false
            },
            {
              type: 'rect',
              left: 0,
              top: 0,
              width: 800,
              height: 120,
              fill: '#3498db',
              stroke: null,
              strokeWidth: 0,
              selectable: false,
              evented: false
            },
            {
              type: 'text',
              left: 400,
              top: 30,
              width: 400,
              height: 40,
              text: 'SARAH JOHNSON',
              fontSize: 28,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#ffffff',
              textAlign: 'center',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 400,
              top: 70,
              width: 400,
              height: 30,
              text: 'Marketing Manager',
              fontSize: 16,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#ecf0f1',
              textAlign: 'center',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 150,
              width: 700,
              height: 20,
              text: 'PROFESSIONAL SUMMARY',
              fontSize: 18,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 180,
              width: 700,
              height: 60,
              text: 'Results-driven marketing professional with 8+ years of experience in digital marketing, brand management, and team leadership. Proven track record of increasing brand awareness and driving revenue growth.',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#34495e',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 260,
              width: 700,
              height: 20,
              text: 'EXPERIENCE',
              fontSize: 18,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 290,
              width: 700,
              height: 40,
              text: 'Senior Marketing Manager | Global Brands Inc. | 2019-Present',
              fontSize: 14,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 330,
              width: 700,
              height: 80,
              text: '• Led digital marketing campaigns resulting in 150% increase in online sales\n• Managed team of 5 marketing specialists and coordinated with cross-functional teams\n• Developed and executed social media strategy growing followers by 200%\n• Implemented marketing automation tools improving lead conversion by 35%',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#34495e',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 430,
              width: 700,
              height: 40,
              text: 'Marketing Manager | TechStart Solutions | 2016-2019',
              fontSize: 14,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 470,
              width: 700,
              height: 80,
              text: '• Launched successful product marketing campaigns for 3 new product lines\n• Increased brand awareness by 80% through strategic content marketing\n• Managed $500K annual marketing budget and achieved 120% ROI\n• Collaborated with sales team to generate $2M in qualified leads',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#34495e',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 570,
              width: 700,
              height: 20,
              text: 'EDUCATION',
              fontSize: 18,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 600,
              width: 700,
              height: 40,
              text: 'Master of Business Administration (MBA)\nNorthwestern University, Kellogg School of Management | 2016',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#34495e',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 660,
              width: 700,
              height: 20,
              text: 'SKILLS',
              fontSize: 18,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 690,
              width: 700,
              height: 60,
              text: 'Digital Marketing, Brand Management, Team Leadership, Marketing Analytics, SEO/SEM, Social Media Marketing, Content Strategy, Marketing Automation, CRM Management, Project Management',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#34495e',
              textAlign: 'left',
              selectable: true,
              evented: true
            }
          ]
        }
      },
      {
        name: 'Data Scientist Resume',
        description: 'Technical data science resume with analytical focus',
        category: 'Professional',
        renderEngine: 'canvas',
        thumbnail: 'https://via.placeholder.com/300x400/1a1a1a/ffffff?text=Data+Scientist',
        preview: 'https://via.placeholder.com/800x1000/1a1a1a/ffffff?text=Data+Scientist+Resume',
        metadata: {
          colorScheme: 'dark',
          layout: 'two-column',
          complexity: 'complex'
        },
        canvasData: {
          version: '5.1.0',
          objects: [
            {
              type: 'rect',
              left: 0,
              top: 0,
              width: 800,
              height: 1000,
              fill: '#ffffff',
              stroke: null,
              strokeWidth: 0,
              selectable: false,
              evented: false
            },
            {
              type: 'rect',
              left: 0,
              top: 0,
              width: 200,
              height: 1000,
              fill: '#1a1a1a',
              stroke: null,
              strokeWidth: 0,
              selectable: false,
              evented: false
            },
            {
              type: 'text',
              left: 100,
              top: 40,
              width: 150,
              height: 40,
              text: 'DR. ALEX CHEN',
              fontSize: 20,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#ffffff',
              textAlign: 'center',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 100,
              top: 80,
              width: 150,
              height: 20,
              text: 'Data Scientist',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#bdc3c7',
              textAlign: 'center',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 100,
              top: 130,
              width: 150,
              height: 20,
              text: 'CONTACT',
              fontSize: 14,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#ffffff',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 100,
              top: 160,
              width: 150,
              height: 80,
              text: 'alex.chen@email.com\n(555) 987-6543\nSeattle, WA\nlinkedin.com/in/alexchen',
              fontSize: 10,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#bdc3c7',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 100,
              top: 270,
              width: 150,
              height: 20,
              text: 'TECHNICAL SKILLS',
              fontSize: 14,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#ffffff',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 100,
              top: 300,
              width: 150,
              height: 120,
              text: 'Python, R, SQL\nMachine Learning\nTensorFlow, PyTorch\nPandas, NumPy, Scikit-learn\nAWS, GCP, Azure\nDocker, Kubernetes\nGit, Jupyter Notebooks',
              fontSize: 10,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#bdc3c7',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 250,
              top: 40,
              width: 500,
              height: 20,
              text: 'PROFESSIONAL SUMMARY',
              fontSize: 16,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#1a1a1a',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 250,
              top: 70,
              width: 500,
              height: 60,
              text: 'Senior Data Scientist with 7+ years of experience in machine learning, statistical analysis, and big data processing. Expert in Python, R, and cloud platforms with a track record of delivering impactful data-driven solutions.',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 250,
              top: 150,
              width: 500,
              height: 20,
              text: 'EXPERIENCE',
              fontSize: 16,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#1a1a1a',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 250,
              top: 180,
              width: 500,
              height: 40,
              text: 'Senior Data Scientist | DataCorp Analytics | 2020-Present',
              fontSize: 14,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#1a1a1a',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 250,
              top: 220,
              width: 500,
              height: 80,
              text: '• Developed ML models improving prediction accuracy by 25% and reducing costs by $2M annually\n• Led team of 4 data scientists and mentored junior analysts\n• Built end-to-end data pipelines processing 10TB+ daily data\n• Presented findings to C-level executives and stakeholders',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 250,
              top: 320,
              width: 500,
              height: 40,
              text: 'Data Scientist | TechStart AI | 2017-2020',
              fontSize: 14,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#1a1a1a',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 250,
              top: 360,
              width: 500,
              height: 80,
              text: '• Created recommendation systems increasing user engagement by 40%\n• Implemented A/B testing framework improving conversion rates by 15%\n• Developed real-time fraud detection models with 99.5% accuracy\n• Collaborated with engineering teams to deploy models in production',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 250,
              top: 460,
              width: 500,
              height: 20,
              text: 'EDUCATION',
              fontSize: 16,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#1a1a1a',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 250,
              top: 490,
              width: 500,
              height: 40,
              text: 'Ph.D. in Statistics | Stanford University | 2017\nM.S. in Computer Science | MIT | 2015',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 250,
              top: 550,
              width: 500,
              height: 20,
              text: 'PUBLICATIONS',
              fontSize: 16,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#1a1a1a',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 250,
              top: 580,
              width: 500,
              height: 60,
              text: '• "Advanced Deep Learning Techniques for Time Series Forecasting" - Journal of Machine Learning Research, 2022\n• "Scalable Machine Learning Pipelines for Big Data" - IEEE Transactions on Knowledge and Data Engineering, 2021',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            }
          ]
        }
      },
      {
        name: 'Graphic Designer Resume',
        description: 'Creative graphic designer resume with artistic layout',
        category: 'Creative',
        renderEngine: 'canvas',
        thumbnail: 'https://via.placeholder.com/300x400/e74c3c/ffffff?text=Graphic+Designer',
        preview: 'https://via.placeholder.com/800x1000/e74c3c/ffffff?text=Graphic+Designer+Resume',
        metadata: {
          colorScheme: 'colorful',
          layout: 'hybrid',
          complexity: 'moderate'
        },
        canvasData: {
          version: '5.1.0',
          objects: [
            {
              type: 'rect',
              left: 0,
              top: 0,
              width: 800,
              height: 1000,
              fill: '#ffffff',
              stroke: null,
              strokeWidth: 0,
              selectable: false,
              evented: false
            },
            {
              type: 'rect',
              left: 0,
              top: 0,
              width: 800,
              height: 100,
              fill: '#e74c3c',
              stroke: null,
              strokeWidth: 0,
              selectable: false,
              evented: false
            },
            {
              type: 'rect',
              left: 0,
              top: 100,
              width: 300,
              height: 900,
              fill: '#f8f9fa',
              stroke: null,
              strokeWidth: 0,
              selectable: false,
              evented: false
            },
            {
              type: 'text',
              left: 400,
              top: 30,
              width: 400,
              height: 40,
              text: 'MIA RODRIGUEZ',
              fontSize: 26,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#ffffff',
              textAlign: 'center',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 400,
              top: 70,
              width: 400,
              height: 20,
              text: 'Graphic Designer & Creative Director',
              fontSize: 14,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#ffffff',
              textAlign: 'center',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 30,
              top: 130,
              width: 250,
              height: 20,
              text: 'CONTACT INFO',
              fontSize: 16,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 30,
              top: 160,
              width: 250,
              height: 80,
              text: 'mia.rodriguez@email.com\n(555) 456-7890\nPortland, OR\nbehance.net/miarodriguez\ninstagram.com/miarodriguez',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#34495e',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 30,
              top: 270,
              width: 250,
              height: 20,
              text: 'DESIGN SKILLS',
              fontSize: 16,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 30,
              top: 300,
              width: 250,
              height: 100,
              text: 'Adobe Creative Suite\nPhotoshop, Illustrator\nInDesign, After Effects\nFigma, Sketch\nUI/UX Design\nBrand Identity\nPrint Design\nWeb Design',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#34495e',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 30,
              top: 430,
              width: 250,
              height: 20,
              text: 'SOFTWARE',
              fontSize: 16,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 30,
              top: 460,
              width: 250,
              height: 60,
              text: 'Adobe Creative Cloud\nFigma, Sketch\nBlender, Cinema 4D\nHTML/CSS\nWordPress',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#34495e',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 350,
              top: 130,
              width: 400,
              height: 20,
              text: 'PROFESSIONAL SUMMARY',
              fontSize: 16,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 350,
              top: 160,
              width: 400,
              height: 60,
              text: 'Creative graphic designer with 6+ years of experience in brand identity, digital design, and print media. Passionate about creating visually compelling designs that communicate effectively and engage audiences.',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#34495e',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 350,
              top: 240,
              width: 400,
              height: 20,
              text: 'EXPERIENCE',
              fontSize: 16,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 350,
              top: 270,
              width: 400,
              height: 40,
              text: 'Senior Graphic Designer | Creative Studio Co. | 2020-Present',
              fontSize: 14,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 350,
              top: 310,
              width: 400,
              height: 80,
              text: '• Led design projects for 50+ clients across various industries\n• Created comprehensive brand identities and style guides\n• Managed junior designers and mentored team members\n• Increased client satisfaction scores by 25%',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#34495e',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 350,
              top: 410,
              width: 400,
              height: 40,
              text: 'Graphic Designer | Digital Agency Pro | 2018-2020',
              fontSize: 14,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 350,
              top: 450,
              width: 400,
              height: 80,
              text: '• Designed websites and mobile apps for tech startups\n• Created marketing materials and social media graphics\n• Collaborated with developers to ensure design feasibility\n• Won 3 design awards for outstanding creative work',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#34495e',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 350,
              top: 550,
              width: 400,
              height: 20,
              text: 'EDUCATION',
              fontSize: 16,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 350,
              top: 580,
              width: 400,
              height: 40,
              text: 'Bachelor of Fine Arts in Graphic Design\nArt Institute of Portland | 2018',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#34495e',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 350,
              top: 640,
              width: 400,
              height: 20,
              text: 'AWARDS & RECOGNITION',
              fontSize: 16,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 350,
              top: 670,
              width: 400,
              height: 60,
              text: '• AIGA Design Excellence Award 2022\n• Adobe Creative Suite Certified Professional\n• Featured in Design Magazine "Rising Stars" 2021',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#34495e',
              textAlign: 'left',
              selectable: true,
              evented: true
            }
          ]
        }
      },
      {
        name: 'Financial Analyst Resume',
        description: 'Professional finance resume with clean corporate layout',
        category: 'Executive',
        renderEngine: 'canvas',
        thumbnail: 'https://via.placeholder.com/300x400/34495e/ffffff?text=Financial+Analyst',
        preview: 'https://via.placeholder.com/800x1000/34495e/ffffff?text=Financial+Analyst+Resume',
        metadata: {
          colorScheme: 'light',
          layout: 'single-column',
          complexity: 'moderate'
        },
        canvasData: {
          version: '5.1.0',
          objects: [
            {
              type: 'rect',
              left: 0,
              top: 0,
              width: 800,
              height: 1000,
              fill: '#ffffff',
              stroke: null,
              strokeWidth: 0,
              selectable: false,
              evented: false
            },
            {
              type: 'rect',
              left: 0,
              top: 0,
              width: 800,
              height: 80,
              fill: '#34495e',
              stroke: null,
              strokeWidth: 0,
              selectable: false,
              evented: false
            },
            {
              type: 'text',
              left: 400,
              top: 25,
              width: 400,
              height: 30,
              text: 'MICHAEL THOMPSON',
              fontSize: 24,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#ffffff',
              textAlign: 'center',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 400,
              top: 55,
              width: 400,
              height: 20,
              text: 'Financial Analyst',
              fontSize: 14,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#ecf0f1',
              textAlign: 'center',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 100,
              width: 700,
              height: 20,
              text: 'PROFESSIONAL SUMMARY',
              fontSize: 18,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 130,
              width: 700,
              height: 60,
              text: 'Detail-oriented financial analyst with 5+ years of experience in financial modeling, budgeting, and investment analysis. Strong analytical skills and expertise in Excel, SQL, and financial software.',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#34495e',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 210,
              width: 700,
              height: 20,
              text: 'EXPERIENCE',
              fontSize: 18,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 240,
              width: 700,
              height: 40,
              text: 'Senior Financial Analyst | Fortune 500 Corp | 2020-Present',
              fontSize: 14,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 280,
              width: 700,
              height: 80,
              text: '• Developed financial models for $50M+ investment decisions\n• Led quarterly budget reviews and variance analysis\n• Created automated reporting dashboards reducing analysis time by 40%\n• Collaborated with cross-functional teams on strategic planning',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#34495e',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 380,
              width: 700,
              height: 40,
              text: 'Financial Analyst | Investment Bank Ltd | 2018-2020',
              fontSize: 14,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 420,
              width: 700,
              height: 80,
              text: '• Analyzed financial statements and market trends for investment recommendations\n• Prepared pitch books and presentations for client meetings\n• Supported M&A transactions worth over $100M\n• Maintained relationships with key stakeholders and clients',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#34495e',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 520,
              width: 700,
              height: 20,
              text: 'EDUCATION',
              fontSize: 18,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 550,
              width: 700,
              height: 40,
              text: 'Master of Business Administration (MBA) - Finance\nUniversity of Chicago, Booth School of Business | 2018',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#34495e',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 610,
              width: 700,
              height: 20,
              text: 'CERTIFICATIONS',
              fontSize: 18,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 640,
              width: 700,
              height: 60,
              text: '• Chartered Financial Analyst (CFA) Level II\n• Certified Public Accountant (CPA)\n• Financial Modeling & Valuation Analyst (FMVA)',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#34495e',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 720,
              width: 700,
              height: 20,
              text: 'TECHNICAL SKILLS',
              fontSize: 18,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 750,
              width: 700,
              height: 60,
              text: 'Excel (Advanced), SQL, Python, Tableau, Power BI, Bloomberg Terminal, SAP, QuickBooks, Financial Modeling, Risk Analysis, Investment Analysis',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#34495e',
              textAlign: 'left',
              selectable: true,
              evented: true
            }
          ]
        }
      }
    ];

    // Insert templates
    for (const template of templates) {
      const newTemplate = new Template(template);
      await newTemplate.save();
      console.log(`✅ Created template: ${template.name}`);
    }

    console.log(`🎉 Successfully created ${templates.length} new resume templates!`);
    
  } catch (error) {
    console.error('❌ Error creating templates:', error);
  } finally {
    await mongoose.disconnect();
    console.log('🔌 Disconnected from MongoDB');
  }
}

createMoreTemplates();
