const mongoose = require('mongoose');
const Template = require('../models/Template');

// MongoDB Atlas connection string
const MONGODB_URI = 'mongodb+srv://balwinder_cvgenix_1998:mAxGheQuqWAyvmzc@cvgenixdb.vrkl6u1.mongodb.net/?retryWrites=true&w=majority&appName=cvgenixdb';

async function createAdditionalTemplates() {
  try {
    await mongoose.connect(MONGODB_URI);
    console.log('✅ Connected to MongoDB Atlas');

    const templates = [
      {
        name: 'Nurse Resume',
        description: 'Professional healthcare resume with clean medical layout',
        category: 'Professional',
        renderEngine: 'canvas',
        thumbnail: 'https://via.placeholder.com/300x400/27ae60/ffffff?text=Registered+Nurse',
        preview: 'https://via.placeholder.com/800x1000/27ae60/ffffff?text=Nurse+Resume',
        metadata: {
          colorScheme: 'light',
          layout: 'single-column',
          complexity: 'simple'
        },
        canvasData: {
          version: '5.1.0',
          objects: [
            {
              type: 'rect',
              left: 0,
              top: 0,
              width: 800,
              height: 1000,
              fill: '#ffffff',
              stroke: null,
              strokeWidth: 0,
              selectable: false,
              evented: false
            },
            {
              type: 'rect',
              left: 0,
              top: 0,
              width: 800,
              height: 100,
              fill: '#27ae60',
              stroke: null,
              strokeWidth: 0,
              selectable: false,
              evented: false
            },
            {
              type: 'text',
              left: 400,
              top: 30,
              width: 400,
              height: 40,
              text: 'JENNIFER MARTINEZ',
              fontSize: 24,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#ffffff',
              textAlign: 'center',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 400,
              top: 70,
              width: 400,
              height: 20,
              text: 'Registered Nurse',
              fontSize: 14,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#ffffff',
              textAlign: 'center',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 120,
              width: 700,
              height: 20,
              text: 'PROFESSIONAL SUMMARY',
              fontSize: 16,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 150,
              width: 700,
              height: 60,
              text: 'Compassionate and dedicated Registered Nurse with 8+ years of experience in patient care, medical procedures, and healthcare coordination. Committed to providing exceptional patient care and improving health outcomes.',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#34495e',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 230,
              width: 700,
              height: 20,
              text: 'EXPERIENCE',
              fontSize: 16,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 260,
              width: 700,
              height: 40,
              text: 'Senior Registered Nurse | City General Hospital | 2019-Present',
              fontSize: 14,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 300,
              width: 700,
              height: 80,
              text: '• Provide direct patient care for 20+ patients daily in medical-surgical unit\n• Mentor new nursing staff and conduct training sessions\n• Collaborate with healthcare team to develop patient care plans\n• Maintain accurate medical records and documentation',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#34495e',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 400,
              width: 700,
              height: 40,
              text: 'Registered Nurse | Community Health Center | 2016-2019',
              fontSize: 14,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 440,
              width: 700,
              height: 80,
              text: '• Administered medications and treatments according to physician orders\n• Conducted patient assessments and vital sign monitoring\n• Educated patients and families on health management\n• Participated in quality improvement initiatives',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#34495e',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 540,
              width: 700,
              height: 20,
              text: 'EDUCATION & CERTIFICATIONS',
              fontSize: 16,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 570,
              width: 700,
              height: 60,
              text: 'Bachelor of Science in Nursing (BSN)\nUniversity of California, Los Angeles | 2016\n\nLicensed Registered Nurse (RN) - California\nBasic Life Support (BLS) Certified\nAdvanced Cardiac Life Support (ACLS) Certified',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#34495e',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 650,
              width: 700,
              height: 20,
              text: 'SKILLS',
              fontSize: 16,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 680,
              width: 700,
              height: 60,
              text: 'Patient Care, Medical Procedures, Medication Administration, Electronic Health Records (EHR), Patient Assessment, IV Therapy, Wound Care, Emergency Response, Team Collaboration, Patient Education',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#34495e',
              textAlign: 'left',
              selectable: true,
              evented: true
            }
          ]
        }
      },
      {
        name: 'Teacher Resume',
        description: 'Educational professional resume with academic focus',
        category: 'Professional',
        renderEngine: 'canvas',
        thumbnail: 'https://via.placeholder.com/300x400/9b59b6/ffffff?text=Teacher',
        preview: 'https://via.placeholder.com/800x1000/9b59b6/ffffff?text=Teacher+Resume',
        metadata: {
          colorScheme: 'light',
          layout: 'single-column',
          complexity: 'simple'
        },
        canvasData: {
          version: '5.1.0',
          objects: [
            {
              type: 'rect',
              left: 0,
              top: 0,
              width: 800,
              height: 1000,
              fill: '#ffffff',
              stroke: null,
              strokeWidth: 0,
              selectable: false,
              evented: false
            },
            {
              type: 'rect',
              left: 0,
              top: 0,
              width: 800,
              height: 80,
              fill: '#9b59b6',
              stroke: null,
              strokeWidth: 0,
              selectable: false,
              evented: false
            },
            {
              type: 'text',
              left: 400,
              top: 25,
              width: 400,
              height: 30,
              text: 'DAVID WILSON',
              fontSize: 22,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#ffffff',
              textAlign: 'center',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 400,
              top: 55,
              width: 400,
              height: 20,
              text: 'Elementary School Teacher',
              fontSize: 14,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#ffffff',
              textAlign: 'center',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 100,
              width: 700,
              height: 20,
              text: 'PROFESSIONAL SUMMARY',
              fontSize: 16,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 130,
              width: 700,
              height: 60,
              text: 'Passionate elementary school teacher with 6+ years of experience fostering student growth and academic achievement. Dedicated to creating engaging learning environments and supporting diverse student needs.',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#34495e',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 210,
              width: 700,
              height: 20,
              text: 'TEACHING EXPERIENCE',
              fontSize: 16,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 240,
              width: 700,
              height: 40,
              text: '3rd Grade Teacher | Lincoln Elementary School | 2018-Present',
              fontSize: 14,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 280,
              width: 700,
              height: 80,
              text: '• Develop and implement engaging curriculum for 25+ students\n• Utilize differentiated instruction to meet diverse learning needs\n• Maintain positive classroom environment and student discipline\n• Collaborate with parents and support staff for student success',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#34495e',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 380,
              width: 700,
              height: 40,
              text: '2nd Grade Teacher | Roosevelt Elementary | 2016-2018',
              fontSize: 14,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 420,
              width: 700,
              height: 80,
              text: '• Created interactive lesson plans incorporating technology\n• Assessed student progress using various evaluation methods\n• Participated in professional development and training programs\n• Organized school events and extracurricular activities',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#34495e',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 520,
              width: 700,
              height: 20,
              text: 'EDUCATION & CERTIFICATIONS',
              fontSize: 16,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 550,
              width: 700,
              height: 60,
              text: 'Master of Education in Elementary Education\nUniversity of Washington | 2016\n\nTeaching Credential - Washington State\nESL Certification\nTechnology Integration Certificate',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#34495e',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 630,
              width: 700,
              height: 20,
              text: 'SPECIALIZATIONS',
              fontSize: 16,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 50,
              top: 660,
              width: 700,
              height: 60,
              text: 'Mathematics Education, Reading Instruction, Special Education Support, Technology Integration, Classroom Management, Parent Communication, Curriculum Development, Student Assessment',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#34495e',
              textAlign: 'left',
              selectable: true,
              evented: true
            }
          ]
        }
      },
      {
        name: 'Sales Manager Resume',
        description: 'Dynamic sales professional resume with results focus',
        category: 'Executive',
        renderEngine: 'canvas',
        thumbnail: 'https://via.placeholder.com/300x400/f39c12/ffffff?text=Sales+Manager',
        preview: 'https://via.placeholder.com/800x1000/f39c12/ffffff?text=Sales+Manager+Resume',
        metadata: {
          colorScheme: 'colorful',
          layout: 'two-column',
          complexity: 'moderate'
        },
        canvasData: {
          version: '5.1.0',
          objects: [
            {
              type: 'rect',
              left: 0,
              top: 0,
              width: 800,
              height: 1000,
              fill: '#ffffff',
              stroke: null,
              strokeWidth: 0,
              selectable: false,
              evented: false
            },
            {
              type: 'rect',
              left: 0,
              top: 0,
              width: 250,
              height: 1000,
              fill: '#f39c12',
              stroke: null,
              strokeWidth: 0,
              selectable: false,
              evented: false
            },
            {
              type: 'text',
              left: 125,
              top: 50,
              width: 200,
              height: 40,
              text: 'ROBERT TAYLOR',
              fontSize: 20,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#ffffff',
              textAlign: 'center',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 125,
              top: 90,
              width: 200,
              height: 20,
              text: 'Sales Manager',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#ffffff',
              textAlign: 'center',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 125,
              top: 140,
              width: 200,
              height: 20,
              text: 'CONTACT',
              fontSize: 14,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#ffffff',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 125,
              top: 170,
              width: 200,
              height: 80,
              text: 'robert.taylor@email.com\n(555) 234-5678\nChicago, IL\nlinkedin.com/in/roberttaylor',
              fontSize: 10,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#ffffff',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 125,
              top: 280,
              width: 200,
              height: 20,
              text: 'ACHIEVEMENTS',
              fontSize: 14,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#ffffff',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 125,
              top: 310,
              width: 200,
              height: 100,
              text: '• $5M+ in sales revenue\n• 150% quota achievement\n• Top 10% performer\n• Team of 8 sales reps',
              fontSize: 10,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#ffffff',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 300,
              top: 50,
              width: 450,
              height: 20,
              text: 'PROFESSIONAL SUMMARY',
              fontSize: 16,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 300,
              top: 80,
              width: 450,
              height: 60,
              text: 'Results-driven sales manager with 10+ years of experience leading high-performing sales teams. Proven track record of exceeding revenue targets and building strong client relationships.',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#34495e',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 300,
              top: 160,
              width: 450,
              height: 20,
              text: 'EXPERIENCE',
              fontSize: 16,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 300,
              top: 190,
              width: 450,
              height: 40,
              text: 'Sales Manager | Tech Solutions Inc. | 2019-Present',
              fontSize: 14,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 300,
              top: 230,
              width: 450,
              height: 80,
              text: '• Led sales team of 8 representatives generating $5M+ annual revenue\n• Developed and implemented sales strategies increasing market share by 30%\n• Built and maintained relationships with key enterprise clients\n• Mentored junior sales staff and conducted performance reviews',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#34495e',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 300,
              top: 330,
              width: 450,
              height: 40,
              text: 'Senior Sales Representative | Global Corp | 2015-2019',
              fontSize: 14,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 300,
              top: 370,
              width: 450,
              height: 80,
              text: '• Exceeded sales targets by 25% consistently for 4 consecutive years\n• Managed portfolio of 50+ enterprise accounts worth $2M+ annually\n• Collaborated with marketing team on lead generation strategies\n• Presented product demonstrations to C-level executives',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#34495e',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 300,
              top: 470,
              width: 450,
              height: 20,
              text: 'EDUCATION',
              fontSize: 16,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 300,
              top: 500,
              width: 450,
              height: 40,
              text: 'Bachelor of Business Administration\nNorthwestern University | 2015',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#34495e',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 300,
              top: 560,
              width: 450,
              height: 20,
              text: 'SKILLS',
              fontSize: 16,
              fontWeight: 'bold',
              fontFamily: 'Arial',
              fill: '#2c3e50',
              textAlign: 'left',
              selectable: true,
              evented: true
            },
            {
              type: 'text',
              left: 300,
              top: 590,
              width: 450,
              height: 60,
              text: 'Sales Management, Team Leadership, CRM Systems, Sales Forecasting, Client Relationship Management, Negotiation, Presentation Skills, Market Analysis, Strategic Planning',
              fontSize: 12,
              fontWeight: 'normal',
              fontFamily: 'Arial',
              fill: '#34495e',
              textAlign: 'left',
              selectable: true,
              evented: true
            }
          ]
        }
      }
    ];

    // Insert templates
    for (const template of templates) {
      const newTemplate = new Template(template);
      await newTemplate.save();
      console.log(`✅ Created template: ${template.name}`);
    }

    console.log(`🎉 Successfully created ${templates.length} additional resume templates!`);
    
  } catch (error) {
    console.error('❌ Error creating templates:', error);
  } finally {
    await mongoose.disconnect();
    console.log('🔌 Disconnected from MongoDB');
  }
}

createAdditionalTemplates();
