const mongoose = require('mongoose');
const Template = require('../models/Template');
require('dotenv').config();

async function createConnorHamiltonTemplate() {
  try {
    // Connect to MongoDB
    console.log('🔌 Connecting to database...');
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('✅ Connected to database');

    // Delete all existing templates
    console.log('🗑️ Deleting all existing templates...');
    const deleteResult = await Template.deleteMany({});
    console.log(`✅ Deleted ${deleteResult.deletedCount} existing templates`);

    // Create Fabric.js canvas data for Connor Hamilton's Real Estate Agent resume
    const fabricCanvasData = {
      version: "5.3.0",
      objects: [
        // Header Section - Centered
        {
          "type": "text",
          "version": "5.3.0",
          "originX": "left",
          "originY": "top",
          "left": 80,
          "top": 60,
          "width": 640,
          "height": 60,
          "fill": "#000000",
          "stroke": null,
          "strokeWidth": 1,
          "strokeDashArray": null,
          "strokeLineCap": "butt",
          "strokeDashOffset": 0,
          "strokeLineJoin": "miter",
          "strokeMiterLimit": 4,
          "scaleX": 1,
          "scaleY": 1,
          "angle": 0,
          "flipX": false,
          "flipY": false,
          "opacity": 1,
          "shadow": null,
          "visible": true,
          "backgroundColor": "",
          "fillRule": "nonzero",
          "paintFirst": "fill",
          "globalCompositeOperation": "source-over",
          "skewX": 0,
          "skewY": 0,
          "text": "CONNOR HAMILTON",
          "fontSize": 48,
          "fontWeight": "900",
          "fontFamily": "Montserrat",
          "fontStyle": "normal",
          "lineHeight": 1,
          "underline": false,
          "overline": false,
          "linethrough": false,
          "textAlign": "center",
          "textBackgroundColor": "",
          "charSpacing": 12,
          "styles": [],
          "path": null,
          "pathStartOffset": 0,
          "pathSide": "left",
          "pathAlign": "baseline",
          "direction": "ltr",
          "minWidth": 20,
          "splitByGrapheme": false,
          "id": "header_name"
        },
        {
          "type": "text",
          "version": "5.3.0",
          "originX": "left",
          "originY": "top",
          "left": 80,
          "top": 135,
          "width": 640,
          "height": 30,
          "fill": "#000000",
          "stroke": null,
          "strokeWidth": 1,
          "strokeDashArray": null,
          "strokeLineCap": "butt",
          "strokeDashOffset": 0,
          "strokeLineJoin": "miter",
          "strokeMiterLimit": 4,
          "scaleX": 1,
          "scaleY": 1,
          "angle": 0,
          "flipX": false,
          "flipY": false,
          "opacity": 1,
          "shadow": null,
          "visible": true,
          "backgroundColor": "",
          "fillRule": "nonzero",
          "paintFirst": "fill",
          "globalCompositeOperation": "source-over",
          "skewX": 0,
          "skewY": 0,
          "text": "Real Estate Agent",
          "fontSize": 18,
          "fontWeight": "600",
          "fontFamily": "Montserrat",
          "fontStyle": "normal",
          "lineHeight": 1,
          "underline": false,
          "overline": false,
          "linethrough": false,
          "textAlign": "center",
          "textBackgroundColor": "",
          "charSpacing": 4,
          "styles": [],
          "path": null,
          "pathStartOffset": 0,
          "pathSide": "left",
          "pathAlign": "baseline",
          "direction": "ltr",
          "minWidth": 20,
          "splitByGrapheme": false,
          "id": "header_title"
        },
        {
          "type": "text",
          "version": "5.3.0",
          "originX": "left",
          "originY": "top",
          "left": 80,
          "top": 175,
          "width": 640,
          "height": 25,
          "fill": "#333333",
          "stroke": null,
          "strokeWidth": 1,
          "strokeDashArray": null,
          "strokeLineCap": "butt",
          "strokeDashOffset": 0,
          "strokeLineJoin": "miter",
          "strokeMiterLimit": 4,
          "scaleX": 1,
          "scaleY": 1,
          "angle": 0,
          "flipX": false,
          "flipY": false,
          "opacity": 1,
          "shadow": null,
          "visible": true,
          "backgroundColor": "",
          "fillRule": "nonzero",
          "paintFirst": "fill",
          "globalCompositeOperation": "source-over",
          "skewX": 0,
          "skewY": 0,
          "text": "123-456-7890  |  hello@reallygreatsite.com  |  reallygreatsite.com",
          "fontSize": 13,
          "fontWeight": "normal",
          "fontFamily": "Montserrat",
          "fontStyle": "italic",
          "lineHeight": 1,
          "underline": false,
          "overline": false,
          "linethrough": false,
          "textAlign": "center",
          "textBackgroundColor": "",
          "charSpacing": 1,
          "styles": [],
          "path": null,
          "pathStartOffset": 0,
          "pathSide": "left",
          "pathAlign": "baseline",
          "direction": "ltr",
          "minWidth": 20,
          "splitByGrapheme": false,
          "id": "header_contact"
        },
        
        // Profile Section
        {
          "type": "text",
          "version": "5.3.0",
          "originX": "left",
          "originY": "top",
          "left": 80,
          "top": 225,
          "width": 200,
          "height": 25,
          "fill": "#000000",
          "stroke": null,
          "strokeWidth": 1,
          "strokeDashArray": null,
          "strokeLineCap": "butt",
          "strokeDashOffset": 0,
          "strokeLineJoin": "miter",
          "strokeMiterLimit": 4,
          "scaleX": 1,
          "scaleY": 1,
          "angle": 0,
          "flipX": false,
          "flipY": false,
          "opacity": 1,
          "shadow": null,
          "visible": true,
          "backgroundColor": "",
          "fillRule": "nonzero",
          "paintFirst": "fill",
          "globalCompositeOperation": "source-over",
          "skewX": 0,
          "skewY": 0,
          "text": "PROFILE",
          "fontSize": 16,
          "fontWeight": "900",
          "fontFamily": "Montserrat",
          "fontStyle": "normal",
          "lineHeight": 1,
          "underline": false,
          "overline": false,
          "linethrough": false,
          "textAlign": "left",
          "textBackgroundColor": "",
          "charSpacing": 4,
          "styles": [],
          "path": null,
          "pathStartOffset": 0,
          "pathSide": "left",
          "pathAlign": "baseline",
          "direction": "ltr",
          "minWidth": 20,
          "splitByGrapheme": false,
          "id": "profile_title"
        },
        {
          "type": "textbox",
          "version": "5.3.0",
          "originX": "left",
          "originY": "top",
          "left": 80,
          "top": 250,
          "width": 640,
          "height": 90,
          "fill": "#333333",
          "stroke": null,
          "strokeWidth": 1,
          "strokeDashArray": null,
          "strokeLineCap": "butt",
          "strokeDashOffset": 0,
          "strokeLineJoin": "miter",
          "strokeMiterLimit": 4,
          "scaleX": 1,
          "scaleY": 1,
          "angle": 0,
          "flipX": false,
          "flipY": false,
          "opacity": 1,
          "shadow": null,
          "visible": true,
          "backgroundColor": "",
          "fillRule": "nonzero",
          "paintFirst": "fill",
          "globalCompositeOperation": "source-over",
          "skewX": 0,
          "skewY": 0,
          "text": "I am an experienced Real Estate Agent with a passion for helping clients find their dream homes. I have extensive experience in the industry, including more than 5 years working as a real estate agent. I am knowledgeable about the latest market trends and understand the nuances of the real estate market. I pride myself on my ability to negotiate the best deals for my clients and to navigate complex real estate agreements. I am highly organized, detail-oriented, and have strong communication skills.",
          "fontSize": 14,
          "fontWeight": "normal",
          "fontFamily": "Montserrat",
          "fontStyle": "normal",
          "lineHeight": 1.5,
          "underline": false,
          "overline": false,
          "linethrough": false,
          "textAlign": "left",
          "textBackgroundColor": "",
          "charSpacing": 0,
          "styles": [],
          "path": null,
          "pathStartOffset": 0,
          "pathSide": "left",
          "pathAlign": "baseline",
          "direction": "ltr",
          "minWidth": 20,
          "splitByGrapheme": false,
          "id": "profile_text"
        },
        
        // Work Experience Section
        {
          "type": "text",
          "version": "5.3.0",
          "originX": "left",
          "originY": "top",
          "left": 80,
          "top": 360,
          "width": 300,
          "height": 25,
          "fill": "#000000",
          "stroke": null,
          "strokeWidth": 1,
          "strokeDashArray": null,
          "strokeLineCap": "butt",
          "strokeDashOffset": 0,
          "strokeLineJoin": "miter",
          "strokeMiterLimit": 4,
          "scaleX": 1,
          "scaleY": 1,
          "angle": 0,
          "flipX": false,
          "flipY": false,
          "opacity": 1,
          "shadow": null,
          "visible": true,
          "backgroundColor": "",
          "fillRule": "nonzero",
          "paintFirst": "fill",
          "globalCompositeOperation": "source-over",
          "skewX": 0,
          "skewY": 0,
          "text": "WORK EXPERIENCE",
          "fontSize": 16,
          "fontWeight": "900",
          "fontFamily": "Montserrat",
          "fontStyle": "normal",
          "lineHeight": 1,
          "underline": false,
          "overline": false,
          "linethrough": false,
          "textAlign": "left",
          "textBackgroundColor": "",
          "charSpacing": 4,
          "styles": [],
          "path": null,
          "pathStartOffset": 0,
          "pathSide": "left",
          "pathAlign": "baseline",
          "direction": "ltr",
          "minWidth": 20,
          "splitByGrapheme": false,
          "id": "work_experience_title"
        },
        {
          "type": "text",
          "version": "5.3.0",
          "originX": "left",
          "originY": "top",
          "left": 80,
          "top": 385,
          "width": 400,
          "height": 20,
          "fill": "#666666",
          "stroke": null,
          "strokeWidth": 1,
          "strokeDashArray": null,
          "strokeLineCap": "butt",
          "strokeDashOffset": 0,
          "strokeLineJoin": "miter",
          "strokeMiterLimit": 4,
          "scaleX": 1,
          "scaleY": 1,
          "angle": 0,
          "flipX": false,
          "flipY": false,
          "opacity": 1,
          "shadow": null,
          "visible": true,
          "backgroundColor": "",
          "fillRule": "nonzero",
          "paintFirst": "fill",
          "globalCompositeOperation": "source-over",
          "skewX": 0,
          "skewY": 0,
          "text": "REAL ESTATE AGENT",
          "fontSize": 12,
          "fontWeight": "600",
          "fontFamily": "Montserrat",
          "fontStyle": "normal",
          "lineHeight": 1,
          "underline": false,
          "overline": false,
          "linethrough": false,
          "textAlign": "left",
          "textBackgroundColor": "",
          "charSpacing": 2,
          "styles": [],
          "path": null,
          "pathStartOffset": 0,
          "pathSide": "left",
          "pathAlign": "baseline",
          "direction": "ltr",
          "minWidth": 20,
          "splitByGrapheme": false,
          "id": "work_job_title"
        },
        {
          "type": "text",
          "version": "5.3.0",
          "originX": "left",
          "originY": "top",
          "left": 80,
          "top": 407,
          "width": 400,
          "height": 25,
          "fill": "#000000",
          "stroke": null,
          "strokeWidth": 1,
          "strokeDashArray": null,
          "strokeLineCap": "butt",
          "strokeDashOffset": 0,
          "strokeLineJoin": "miter",
          "strokeMiterLimit": 4,
          "scaleX": 1,
          "scaleY": 1,
          "angle": 0,
          "flipX": false,
          "flipY": false,
          "opacity": 1,
          "shadow": null,
          "visible": true,
          "backgroundColor": "",
          "fillRule": "nonzero",
          "paintFirst": "fill",
          "globalCompositeOperation": "source-over",
          "skewX": 0,
          "skewY": 0,
          "text": "Really Great Company",
          "fontSize": 15,
          "fontWeight": "700",
          "fontFamily": "Montserrat",
          "fontStyle": "normal",
          "lineHeight": 1,
          "underline": false,
          "overline": false,
          "linethrough": false,
          "textAlign": "left",
          "textBackgroundColor": "",
          "charSpacing": 0,
          "styles": [],
          "path": null,
          "pathStartOffset": 0,
          "pathSide": "left",
          "pathAlign": "baseline",
          "direction": "ltr",
          "minWidth": 20,
          "splitByGrapheme": false,
          "id": "work_company"
        },
        {
          "type": "text",
          "version": "5.3.0",
          "originX": "left",
          "originY": "top",
          "left": 80,
          "top": 430,
          "width": 400,
          "height": 20,
          "fill": "#666666",
          "stroke": null,
          "strokeWidth": 1,
          "strokeDashArray": null,
          "strokeLineCap": "butt",
          "strokeDashOffset": 0,
          "strokeLineJoin": "miter",
          "strokeMiterLimit": 4,
          "scaleX": 1,
          "scaleY": 1,
          "angle": 0,
          "flipX": false,
          "flipY": false,
          "opacity": 1,
          "shadow": null,
          "visible": true,
          "backgroundColor": "",
          "fillRule": "nonzero",
          "paintFirst": "fill",
          "globalCompositeOperation": "source-over",
          "skewX": 0,
          "skewY": 0,
          "text": "June 2015 - Present",
          "fontSize": 13,
          "fontWeight": "normal",
          "fontFamily": "Montserrat",
          "fontStyle": "italic",
          "lineHeight": 1,
          "underline": false,
          "overline": false,
          "linethrough": false,
          "textAlign": "left",
          "textBackgroundColor": "",
          "charSpacing": 0,
          "styles": [],
          "path": null,
          "pathStartOffset": 0,
          "pathSide": "left",
          "pathAlign": "baseline",
          "direction": "ltr",
          "minWidth": 20,
          "splitByGrapheme": false,
          "id": "work_dates"
        },
        
        // Work Experience Bullet Points
        {
          "type": "textbox",
          "version": "5.3.0",
          "originX": "left",
          "originY": "top",
          "left": 80,
          "top": 460,
          "width": 640,
          "height": 120,
          "fill": "#333333",
          "stroke": null,
          "strokeWidth": 1,
          "strokeDashArray": null,
          "strokeLineCap": "butt",
          "strokeDashOffset": 0,
          "strokeLineJoin": "miter",
          "strokeMiterLimit": 4,
          "scaleX": 1,
          "scaleY": 1,
          "angle": 0,
          "flipX": false,
          "flipY": false,
          "opacity": 1,
          "shadow": null,
          "visible": true,
          "backgroundColor": "",
          "fillRule": "nonzero",
          "paintFirst": "fill",
          "globalCompositeOperation": "source-over",
          "skewX": 0,
          "skewY": 0,
          "text": "• Negotiate contracts and complex real estate transactions\n• Provide excellent customer service to clients\n• Update and maintain client files\n• Research and monitor the local real estate market\n• Develop marketing campaigns for properties\n• Utilize social media platforms to market properties\n• Participate in open houses and home tours",
          "fontSize": 13,
          "fontWeight": "normal",
          "fontFamily": "Montserrat",
          "fontStyle": "normal",
          "lineHeight": 1.4,
          "underline": false,
          "overline": false,
          "linethrough": false,
          "textAlign": "left",
          "textBackgroundColor": "",
          "charSpacing": 0,
          "styles": [],
          "path": null,
          "pathStartOffset": 0,
          "pathSide": "left",
          "pathAlign": "baseline",
          "direction": "ltr",
          "minWidth": 20,
          "splitByGrapheme": false,
          "id": "work_bullets"
        },
        
        // Education Section
        {
          "type": "text",
          "version": "5.3.0",
          "originX": "left",
          "originY": "top",
          "left": 80,
          "top": 600,
          "width": 200,
          "height": 25,
          "fill": "#000000",
          "stroke": null,
          "strokeWidth": 1,
          "strokeDashArray": null,
          "strokeLineCap": "butt",
          "strokeDashOffset": 0,
          "strokeLineJoin": "miter",
          "strokeMiterLimit": 4,
          "scaleX": 1,
          "scaleY": 1,
          "angle": 0,
          "flipX": false,
          "flipY": false,
          "opacity": 1,
          "shadow": null,
          "visible": true,
          "backgroundColor": "",
          "fillRule": "nonzero",
          "paintFirst": "fill",
          "globalCompositeOperation": "source-over",
          "skewX": 0,
          "skewY": 0,
          "text": "EDUCATION",
          "fontSize": 16,
          "fontWeight": "900",
          "fontFamily": "Montserrat",
          "fontStyle": "normal",
          "lineHeight": 1,
          "underline": false,
          "overline": false,
          "linethrough": false,
          "textAlign": "left",
          "textBackgroundColor": "",
          "charSpacing": 4,
          "styles": [],
          "path": null,
          "pathStartOffset": 0,
          "pathSide": "left",
          "pathAlign": "baseline",
          "direction": "ltr",
          "minWidth": 20,
          "splitByGrapheme": false,
          "id": "education_title"
        },
        {
          "type": "text",
          "version": "5.3.0",
          "originX": "left",
          "originY": "top",
          "left": 80,
          "top": 625,
          "width": 300,
          "height": 20,
          "fill": "#000000",
          "stroke": null,
          "strokeWidth": 1,
          "strokeDashArray": null,
          "strokeLineCap": "butt",
          "strokeDashOffset": 0,
          "strokeLineJoin": "miter",
          "strokeMiterLimit": 4,
          "scaleX": 1,
          "scaleY": 1,
          "angle": 0,
          "flipX": false,
          "flipY": false,
          "opacity": 1,
          "shadow": null,
          "visible": true,
          "backgroundColor": "",
          "fillRule": "nonzero",
          "paintFirst": "fill",
          "globalCompositeOperation": "source-over",
          "skewX": 0,
          "skewY": 0,
          "text": "University",
          "fontSize": 15,
          "fontWeight": "700",
          "fontFamily": "Montserrat",
          "fontStyle": "normal",
          "lineHeight": 1,
          "underline": false,
          "overline": false,
          "linethrough": false,
          "textAlign": "left",
          "textBackgroundColor": "",
          "charSpacing": 0,
          "styles": [],
          "path": null,
          "pathStartOffset": 0,
          "pathSide": "left",
          "pathAlign": "baseline",
          "direction": "ltr",
          "minWidth": 20,
          "splitByGrapheme": false,
          "id": "education_school"
        },
        {
          "type": "text",
          "version": "5.3.0",
          "originX": "left",
          "originY": "top",
          "left": 80,
          "top": 645,
          "width": 300,
          "height": 20,
          "fill": "#666666",
          "stroke": null,
          "strokeWidth": 1,
          "strokeDashArray": null,
          "strokeLineCap": "butt",
          "strokeDashOffset": 0,
          "strokeLineJoin": "miter",
          "strokeMiterLimit": 4,
          "scaleX": 1,
          "scaleY": 1,
          "angle": 0,
          "flipX": false,
          "flipY": false,
          "opacity": 1,
          "shadow": null,
          "visible": true,
          "backgroundColor": "",
          "fillRule": "nonzero",
          "paintFirst": "fill",
          "globalCompositeOperation": "source-over",
          "skewX": 0,
          "skewY": 0,
          "text": "2010 - 2014",
          "fontSize": 13,
          "fontWeight": "normal",
          "fontFamily": "Montserrat",
          "fontStyle": "italic",
          "lineHeight": 1,
          "underline": false,
          "overline": false,
          "linethrough": false,
          "textAlign": "left",
          "textBackgroundColor": "",
          "charSpacing": 0,
          "styles": [],
          "path": null,
          "pathStartOffset": 0,
          "pathSide": "left",
          "pathAlign": "baseline",
          "direction": "ltr",
          "minWidth": 20,
          "splitByGrapheme": false,
          "id": "education_dates"
        },
        {
          "type": "text",
          "version": "5.3.0",
          "originX": "left",
          "originY": "top",
          "left": 80,
          "top": 665,
          "width": 300,
          "height": 20,
          "fill": "#333333",
          "stroke": null,
          "strokeWidth": 1,
          "strokeDashArray": null,
          "strokeLineCap": "butt",
          "strokeDashOffset": 0,
          "strokeLineJoin": "miter",
          "strokeMiterLimit": 4,
          "scaleX": 1,
          "scaleY": 1,
          "angle": 0,
          "flipX": false,
          "flipY": false,
          "opacity": 1,
          "shadow": null,
          "visible": true,
          "backgroundColor": "",
          "fillRule": "nonzero",
          "paintFirst": "fill",
          "globalCompositeOperation": "source-over",
          "skewX": 0,
          "skewY": 0,
          "text": "B.A. in Business Administration",
          "fontSize": 14,
          "fontWeight": "normal",
          "fontFamily": "Montserrat",
          "fontStyle": "normal",
          "lineHeight": 1,
          "underline": false,
          "overline": false,
          "linethrough": false,
          "textAlign": "left",
          "textBackgroundColor": "",
          "charSpacing": 0,
          "styles": [],
          "path": null,
          "pathStartOffset": 0,
          "pathSide": "left",
          "pathAlign": "baseline",
          "direction": "ltr",
          "minWidth": 20,
          "splitByGrapheme": false,
          "id": "education_degree"
        },
        
        // Skills Section
        {
          "type": "text",
          "version": "5.3.0",
          "originX": "left",
          "originY": "top",
          "left": 400,
          "top": 600,
          "width": 200,
          "height": 25,
          "fill": "#000000",
          "stroke": null,
          "strokeWidth": 1,
          "strokeDashArray": null,
          "strokeLineCap": "butt",
          "strokeDashOffset": 0,
          "strokeLineJoin": "miter",
          "strokeMiterLimit": 4,
          "scaleX": 1,
          "scaleY": 1,
          "angle": 0,
          "flipX": false,
          "flipY": false,
          "opacity": 1,
          "shadow": null,
          "visible": true,
          "backgroundColor": "",
          "fillRule": "nonzero",
          "paintFirst": "fill",
          "globalCompositeOperation": "source-over",
          "skewX": 0,
          "skewY": 0,
          "text": "SKILLS",
          "fontSize": 16,
          "fontWeight": "900",
          "fontFamily": "Montserrat",
          "fontStyle": "normal",
          "lineHeight": 1,
          "underline": false,
          "overline": false,
          "linethrough": false,
          "textAlign": "left",
          "textBackgroundColor": "",
          "charSpacing": 4,
          "styles": [],
          "path": null,
          "pathStartOffset": 0,
          "pathSide": "left",
          "pathAlign": "baseline",
          "direction": "ltr",
          "minWidth": 20,
          "splitByGrapheme": false,
          "id": "skills_title"
        },
        {
          "type": "textbox",
          "version": "5.3.0",
          "originX": "left",
          "originY": "top",
          "left": 400,
          "top": 625,
          "width": 320,
          "height": 100,
          "fill": "#333333",
          "stroke": null,
          "strokeWidth": 1,
          "strokeDashArray": null,
          "strokeLineCap": "butt",
          "strokeDashOffset": 0,
          "strokeLineJoin": "miter",
          "strokeMiterLimit": 4,
          "scaleX": 1,
          "scaleY": 1,
          "angle": 0,
          "flipX": false,
          "flipY": false,
          "opacity": 1,
          "shadow": null,
          "visible": true,
          "backgroundColor": "",
          "fillRule": "nonzero",
          "paintFirst": "fill",
          "globalCompositeOperation": "source-over",
          "skewX": 0,
          "skewY": 0,
          "text": "• Knowledge of the local real estate market\n• Communication skills\n• Negotiation skills\n• Problem-solving skills\n• Organization and time management skills",
          "fontSize": 13,
          "fontWeight": "normal",
          "fontFamily": "Montserrat",
          "fontStyle": "normal",
          "lineHeight": 1.4,
          "underline": false,
          "overline": false,
          "linethrough": false,
          "textAlign": "left",
          "textBackgroundColor": "",
          "charSpacing": 0,
          "styles": [],
          "path": null,
          "pathStartOffset": 0,
          "pathSide": "left",
          "pathAlign": "baseline",
          "direction": "ltr",
          "minWidth": 20,
          "splitByGrapheme": false,
          "id": "skills_list"
        },
        
        // Certifications Section
        {
          "type": "text",
          "version": "5.3.0",
          "originX": "left",
          "originY": "top",
          "left": 80,
          "top": 700,
          "width": 200,
          "height": 25,
          "fill": "#000000",
          "stroke": null,
          "strokeWidth": 1,
          "strokeDashArray": null,
          "strokeLineCap": "butt",
          "strokeDashOffset": 0,
          "strokeLineJoin": "miter",
          "strokeMiterLimit": 4,
          "scaleX": 1,
          "scaleY": 1,
          "angle": 0,
          "flipX": false,
          "flipY": false,
          "opacity": 1,
          "shadow": null,
          "visible": true,
          "backgroundColor": "",
          "fillRule": "nonzero",
          "paintFirst": "fill",
          "globalCompositeOperation": "source-over",
          "skewX": 0,
          "skewY": 0,
          "text": "CERTIFICATIONS",
          "fontSize": 16,
          "fontWeight": "900",
          "fontFamily": "Montserrat",
          "fontStyle": "normal",
          "lineHeight": 1,
          "underline": false,
          "overline": false,
          "linethrough": false,
          "textAlign": "left",
          "textBackgroundColor": "",
          "charSpacing": 4,
          "styles": [],
          "path": null,
          "pathStartOffset": 0,
          "pathSide": "left",
          "pathAlign": "baseline",
          "direction": "ltr",
          "minWidth": 20,
          "splitByGrapheme": false,
          "id": "certifications_title"
        },
        {
          "type": "textbox",
          "version": "5.3.0",
          "originX": "left",
          "originY": "top",
          "left": 80,
          "top": 725,
          "width": 300,
          "height": 80,
          "fill": "#333333",
          "stroke": null,
          "strokeWidth": 1,
          "strokeDashArray": null,
          "strokeLineCap": "butt",
          "strokeDashOffset": 0,
          "strokeLineJoin": "miter",
          "strokeMiterLimit": 4,
          "scaleX": 1,
          "scaleY": 1,
          "angle": 0,
          "flipX": false,
          "flipY": false,
          "opacity": 1,
          "shadow": null,
          "visible": true,
          "backgroundColor": "",
          "fillRule": "nonzero",
          "paintFirst": "fill",
          "globalCompositeOperation": "source-over",
          "skewX": 0,
          "skewY": 0,
          "text": "• Licensed Real Estate Agent\n• Certified Real Estate Negotiator\n• Top Sales Agent Award 2016",
          "fontSize": 13,
          "fontWeight": "normal",
          "fontFamily": "Montserrat",
          "fontStyle": "normal",
          "lineHeight": 1.4,
          "underline": false,
          "overline": false,
          "linethrough": false,
          "textAlign": "left",
          "textBackgroundColor": "",
          "charSpacing": 0,
          "styles": [],
          "path": null,
          "pathStartOffset": 0,
          "pathSide": "left",
          "pathAlign": "baseline",
          "direction": "ltr",
          "minWidth": 20,
          "splitByGrapheme": false,
          "id": "certifications_list"
        }
      ]
    };

    // Create the Real Estate Agent template with Connor Hamilton's data
    const realEstateTemplate = new Template({
      name: "Real Estate Agent Template",
      description: "Professional resume template designed specifically for real estate agents and property professionals",
      category: "Professional",
      thumbnail: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==",
      preview: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==",
      renderEngine: "canvas",
      isActive: true,
      isPremium: false,
      isPopular: true,
      isNewTemplate: true,
      tags: ["real-estate", "professional", "sales", "property", "agent", "connor-hamilton"],
      metadata: {
        colorScheme: "light",
        layout: "single-column",
        complexity: "moderate"
      },
      canvasData: fabricCanvasData
    });

    await realEstateTemplate.save();
    console.log('✅ Real Estate Agent template with Connor Hamilton data created successfully');

    // Verify the template
    const totalTemplates = await Template.countDocuments();
    console.log(`📊 Total templates in database: ${totalTemplates}`);
    console.log(`📝 Template ID: ${realEstateTemplate._id}`);
    console.log(`📝 Template Name: ${realEstateTemplate.name}`);
    console.log(`📝 Canvas Objects: ${realEstateTemplate.canvasData.objects.length}`);

  } catch (error) {
    console.error('❌ Error:', error.message);
    process.exit(1);
  } finally {
    await mongoose.connection.close();
    console.log('🔌 Database connection closed');
    process.exit(0);
  }
}

// Run the script
createConnorHamiltonTemplate();
