const mongoose = require('mongoose');
const Template = require('../models/Template');
const axios = require('axios');

async function createRealEstateTemplateFabric() {
  try {
    // Connect to MongoDB
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB');

    // Delete existing templates
    await Template.deleteMany({});
    console.log('Deleted existing templates from database');

    // Download and process thumbnail
    console.log('Downloading thumbnail image...');
    const thumbnailResponse = await axios.get('https://marketplace.canva.com/EAFqM-si0PA/2/0/1131w/canva-6NmyGFO0pBE.jpg', {
      responseType: 'arraybuffer'
    });
    const thumbnailBuffer = Buffer.from(thumbnailResponse.data);
    const thumbnailBase64 = `data:image/jpeg;base64,${thumbnailBuffer.toString('base64')}`;
    
    // Create preview (same as thumbnail for now)
    const previewBase64 = thumbnailBase64;

    console.log('Creating Real Estate Agent template with Fabric.js format...');

    // Create Fabric.js canvas data
    const fabricCanvasData = {
      version: "5.3.0",
      objects: [
        // Header Section - Centered
        {
          "type": "text",
          "version": "5.3.0",
          "originX": "left",
          "originY": "top",
          "left": 80,
          "top": 60,
          "width": 640,
          "height": 60,
          "fill": "#000000",
          "stroke": null,
          "strokeWidth": 1,
          "strokeDashArray": null,
          "strokeLineCap": "butt",
          "strokeDashOffset": 0,
          "strokeLineJoin": "miter",
          "strokeMiterLimit": 4,
          "scaleX": 1,
          "scaleY": 1,
          "angle": 0,
          "flipX": false,
          "flipY": false,
          "opacity": 1,
          "shadow": null,
          "visible": true,
          "backgroundColor": "",
          "fillRule": "nonzero",
          "paintFirst": "fill",
          "globalCompositeOperation": "source-over",
          "skewX": 0,
          "skewY": 0,
          "text": "CONNOR HAMILTON",
          "fontSize": 48,
          "fontWeight": "900",
          "fontFamily": "Montserrat",
          "fontStyle": "normal",
          "lineHeight": 1,
          "underline": false,
          "overline": false,
          "linethrough": false,
          "textAlign": "center",
          "textBackgroundColor": "",
          "charSpacing": 12,
          "styles": [],
          "path": null,
          "pathStartOffset": 0,
          "pathSide": "left",
          "pathAlign": "baseline",
          "direction": "ltr",
          "minWidth": 20,
          "splitByGrapheme": false,
          "id": "header_name"
        },
        {
          "type": "text",
          "version": "5.3.0",
          "originX": "left",
          "originY": "top",
          "left": 80,
          "top": 135,
          "width": 640,
          "height": 30,
          "fill": "#000000",
          "stroke": null,
          "strokeWidth": 1,
          "strokeDashArray": null,
          "strokeLineCap": "butt",
          "strokeDashOffset": 0,
          "strokeLineJoin": "miter",
          "strokeMiterLimit": 4,
          "scaleX": 1,
          "scaleY": 1,
          "angle": 0,
          "flipX": false,
          "flipY": false,
          "opacity": 1,
          "shadow": null,
          "visible": true,
          "backgroundColor": "",
          "fillRule": "nonzero",
          "paintFirst": "fill",
          "globalCompositeOperation": "source-over",
          "skewX": 0,
          "skewY": 0,
          "text": "Real Estate Agent",
          "fontSize": 18,
          "fontWeight": "600",
          "fontFamily": "Montserrat",
          "fontStyle": "normal",
          "lineHeight": 1,
          "underline": false,
          "overline": false,
          "linethrough": false,
          "textAlign": "center",
          "textBackgroundColor": "",
          "charSpacing": 4,
          "styles": [],
          "path": null,
          "pathStartOffset": 0,
          "pathSide": "left",
          "pathAlign": "baseline",
          "direction": "ltr",
          "minWidth": 20,
          "splitByGrapheme": false,
          "id": "header_title"
        },
        {
          "type": "text",
          "version": "5.3.0",
          "originX": "left",
          "originY": "top",
          "left": 80,
          "top": 175,
          "width": 640,
          "height": 25,
          "fill": "#333333",
          "stroke": null,
          "strokeWidth": 1,
          "strokeDashArray": null,
          "strokeLineCap": "butt",
          "strokeDashOffset": 0,
          "strokeLineJoin": "miter",
          "strokeMiterLimit": 4,
          "scaleX": 1,
          "scaleY": 1,
          "angle": 0,
          "flipX": false,
          "flipY": false,
          "opacity": 1,
          "shadow": null,
          "visible": true,
          "backgroundColor": "",
          "fillRule": "nonzero",
          "paintFirst": "fill",
          "globalCompositeOperation": "source-over",
          "skewX": 0,
          "skewY": 0,
          "text": "123-456-7890 / hello@reallygreatsite.com | reallygreatsite.com",
          "fontSize": 13,
          "fontWeight": "normal",
          "fontFamily": "Montserrat",
          "fontStyle": "italic",
          "lineHeight": 1,
          "underline": false,
          "overline": false,
          "linethrough": false,
          "textAlign": "center",
          "textBackgroundColor": "",
          "charSpacing": 1,
          "styles": [],
          "path": null,
          "pathStartOffset": 0,
          "pathSide": "left",
          "pathAlign": "baseline",
          "direction": "ltr",
          "minWidth": 20,
          "splitByGrapheme": false,
          "id": "header_contact"
        },
        
        // Profile Section
        {
          "type": "text",
          "version": "5.3.0",
          "originX": "left",
          "originY": "top",
          "left": 80,
          "top": 225,
          "width": 200,
          "height": 25,
          "fill": "#000000",
          "stroke": null,
          "strokeWidth": 1,
          "strokeDashArray": null,
          "strokeLineCap": "butt",
          "strokeDashOffset": 0,
          "strokeLineJoin": "miter",
          "strokeMiterLimit": 4,
          "scaleX": 1,
          "scaleY": 1,
          "angle": 0,
          "flipX": false,
          "flipY": false,
          "opacity": 1,
          "shadow": null,
          "visible": true,
          "backgroundColor": "",
          "fillRule": "nonzero",
          "paintFirst": "fill",
          "globalCompositeOperation": "source-over",
          "skewX": 0,
          "skewY": 0,
          "text": "PROFILE",
          "fontSize": 16,
          "fontWeight": "900",
          "fontFamily": "Montserrat",
          "fontStyle": "normal",
          "lineHeight": 1,
          "underline": false,
          "overline": false,
          "linethrough": false,
          "textAlign": "left",
          "textBackgroundColor": "",
          "charSpacing": 4,
          "styles": [],
          "path": null,
          "pathStartOffset": 0,
          "pathSide": "left",
          "pathAlign": "baseline",
          "direction": "ltr",
          "minWidth": 20,
          "splitByGrapheme": false,
          "id": "profile_title"
        },
        {
          "type": "textbox",
          "version": "5.3.0",
          "originX": "left",
          "originY": "top",
          "left": 80,
          "top": 250,
          "width": 640,
          "height": 90,
          "fill": "#333333",
          "stroke": null,
          "strokeWidth": 1,
          "strokeDashArray": null,
          "strokeLineCap": "butt",
          "strokeDashOffset": 0,
          "strokeLineJoin": "miter",
          "strokeMiterLimit": 4,
          "scaleX": 1,
          "scaleY": 1,
          "angle": 0,
          "flipX": false,
          "flipY": false,
          "opacity": 1,
          "shadow": null,
          "visible": true,
          "backgroundColor": "",
          "fillRule": "nonzero",
          "paintFirst": "fill",
          "globalCompositeOperation": "source-over",
          "skewX": 0,
          "skewY": 0,
          "text": "I am an experienced Real Estate Agent with a passion for helping clients find their dream homes. I have extensive experience in the industry, including more than 5 years working as a real estate agent.\n\nI am knowledgeable about the latest market trends and understand the nuances of the real estate market. I pride myself on my ability to negotiate the best deals for my clients and to navigate complex real estate agreements.\n\nI am highly organized, detail-oriented, and have strong communication skills.",
          "fontSize": 14,
          "fontWeight": "normal",
          "fontFamily": "Montserrat",
          "fontStyle": "normal",
          "lineHeight": 1.5,
          "underline": false,
          "overline": false,
          "linethrough": false,
          "textAlign": "left",
          "textBackgroundColor": "",
          "charSpacing": 0,
          "styles": [],
          "path": null,
          "pathStartOffset": 0,
          "pathSide": "left",
          "pathAlign": "baseline",
          "direction": "ltr",
          "minWidth": 20,
          "splitByGrapheme": false,
          "id": "profile_text"
        },
        // Work Experience Section
        {
          "type": "text",
          "version": "5.3.0",
          "originX": "left",
          "originY": "top",
          "left": 80,
          "top": 360,
          "width": 300,
          "height": 25,
          "fill": "#000000",
          "stroke": null,
          "strokeWidth": 1,
          "strokeDashArray": null,
          "strokeLineCap": "butt",
          "strokeDashOffset": 0,
          "strokeLineJoin": "miter",
          "strokeMiterLimit": 4,
          "scaleX": 1,
          "scaleY": 1,
          "angle": 0,
          "flipX": false,
          "flipY": false,
          "opacity": 1,
          "shadow": null,
          "visible": true,
          "backgroundColor": "",
          "fillRule": "nonzero",
          "paintFirst": "fill",
          "globalCompositeOperation": "source-over",
          "skewX": 0,
          "skewY": 0,
          "text": "WORK EXPERIENCE",
          "fontSize": 16,
          "fontWeight": "900",
          "fontFamily": "Montserrat",
          "fontStyle": "normal",
          "lineHeight": 1,
          "underline": false,
          "overline": false,
          "linethrough": false,
          "textAlign": "left",
          "textBackgroundColor": "",
          "charSpacing": 4,
          "styles": [],
          "path": null,
          "pathStartOffset": 0,
          "pathSide": "left",
          "pathAlign": "baseline",
          "direction": "ltr",
          "minWidth": 20,
          "splitByGrapheme": false,
          "id": "work_experience_title"
        },
        {
          "type": "text",
          "version": "5.3.0",
          "originX": "left",
          "originY": "top",
          "left": 80,
          "top": 385,
          "width": 400,
          "height": 20,
          "fill": "#666666",
          "stroke": null,
          "strokeWidth": 1,
          "strokeDashArray": null,
          "strokeLineCap": "butt",
          "strokeDashOffset": 0,
          "strokeLineJoin": "miter",
          "strokeMiterLimit": 4,
          "scaleX": 1,
          "scaleY": 1,
          "angle": 0,
          "flipX": false,
          "flipY": false,
          "opacity": 1,
          "shadow": null,
          "visible": true,
          "backgroundColor": "",
          "fillRule": "nonzero",
          "paintFirst": "fill",
          "globalCompositeOperation": "source-over",
          "skewX": 0,
          "skewY": 0,
          "text": "REAL ESTATE AGENT",
          "fontSize": 12,
          "fontWeight": "600",
          "fontFamily": "Montserrat",
          "fontStyle": "normal",
          "lineHeight": 1,
          "underline": false,
          "overline": false,
          "linethrough": false,
          "textAlign": "left",
          "textBackgroundColor": "",
          "charSpacing": 2,
          "styles": [],
          "path": null,
          "pathStartOffset": 0,
          "pathSide": "left",
          "pathAlign": "baseline",
          "direction": "ltr",
          "minWidth": 20,
          "splitByGrapheme": false,
          "id": "work_job_title"
        },
        {
          "type": "text",
          "version": "5.3.0",
          "originX": "left",
          "originY": "top",
          "left": 80,
          "top": 407,
          "width": 400,
          "height": 25,
          "fill": "#000000",
          "stroke": null,
          "strokeWidth": 1,
          "strokeDashArray": null,
          "strokeLineCap": "butt",
          "strokeDashOffset": 0,
          "strokeLineJoin": "miter",
          "strokeMiterLimit": 4,
          "scaleX": 1,
          "scaleY": 1,
          "angle": 0,
          "flipX": false,
          "flipY": false,
          "opacity": 1,
          "shadow": null,
          "visible": true,
          "backgroundColor": "",
          "fillRule": "nonzero",
          "paintFirst": "fill",
          "globalCompositeOperation": "source-over",
          "skewX": 0,
          "skewY": 0,
          "text": "Really Great Company",
          "fontSize": 15,
          "fontWeight": "700",
          "fontFamily": "Montserrat",
          "fontStyle": "normal",
          "lineHeight": 1,
          "underline": false,
          "overline": false,
          "linethrough": false,
          "textAlign": "left",
          "textBackgroundColor": "",
          "charSpacing": 0,
          "styles": [],
          "path": null,
          "pathStartOffset": 0,
          "pathSide": "left",
          "pathAlign": "baseline",
          "direction": "ltr",
          "minWidth": 20,
          "splitByGrapheme": false,
          "id": "work_company"
        },
        {
          "type": "text",
          "version": "5.3.0",
          "originX": "left",
          "originY": "top",
          "left": 80,
          "top": 430,
          "width": 400,
          "height": 20,
          "fill": "#666666",
          "stroke": null,
          "strokeWidth": 1,
          "strokeDashArray": null,
          "strokeLineCap": "butt",
          "strokeDashOffset": 0,
          "strokeLineJoin": "miter",
          "strokeMiterLimit": 4,
          "scaleX": 1,
          "scaleY": 1,
          "angle": 0,
          "flipX": false,
          "flipY": false,
          "opacity": 1,
          "shadow": null,
          "visible": true,
          "backgroundColor": "",
          "fillRule": "nonzero",
          "paintFirst": "fill",
          "globalCompositeOperation": "source-over",
          "skewX": 0,
          "skewY": 0,
          "text": "June 2015 - Present",
          "fontSize": 13,
          "fontWeight": "normal",
          "fontFamily": "Montserrat",
          "fontStyle": "italic",
          "lineHeight": 1,
          "underline": false,
          "overline": false,
          "linethrough": false,
          "textAlign": "left",
          "textBackgroundColor": "",
          "charSpacing": 0,
          "styles": [],
          "path": null,
          "pathStartOffset": 0,
          "pathSide": "left",
          "pathAlign": "baseline",
          "direction": "ltr",
          "minWidth": 20,
          "splitByGrapheme": false,
          "id": "work_dates"
        }
      ]
    };

    // Create the Real Estate Agent template
    const realEstateTemplate = new Template({
      name: "Real Estate Agent Template",
      description: "Professional resume template designed specifically for real estate agents and property professionals",
      category: "Professional",
      thumbnail: thumbnailBase64,
      preview: previewBase64,
      renderEngine: "canvas",
      isActive: true,
      isPremium: false,
      isPopular: true,
      isNewTemplate: true,
      tags: ["real-estate", "professional", "sales", "property", "agent"],
      metadata: {
        colorScheme: "light",
        layout: "single-column",
        complexity: "moderate"
      },
      canvasData: fabricCanvasData
    });

    await realEstateTemplate.save();
    console.log('✅ Real Estate Agent template created successfully with Fabric.js format');

    // Verify the template
    const totalTemplates = await Template.countDocuments();
    console.log(`📊 Total templates in database: ${totalTemplates}`);
    console.log(`📝 Template ID: ${realEstateTemplate._id}`);
    console.log(`📝 Template Name: ${realEstateTemplate.name}`);
    console.log(`📝 Canvas Objects: ${realEstateTemplate.canvasData.objects.length}`);

  } catch (error) {
    console.error('❌ Error:', error.message);
  } finally {
    await mongoose.connection.close();
    console.log('🔌 Database connection closed');
  }
}

createRealEstateTemplateFabric();
